# Generated by Django 2.0.1 on 2018-01-29 05:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_auto_20180129_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='liker_set',
            field=models.ManyToManyField(related_name='liked_article_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='core.Tag'),
        ),
    ]
